import "dotenv/config"
import { PrismaClient } from "../src/generated/prisma/client"
import { PrismaPg } from "@prisma/adapter-pg"
import bcrypt from "bcryptjs"

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! })
const prisma = new PrismaClient({ adapter })

async function main() {
  // Admin user
  const adminPassword = await bcrypt.hash("admin123", 12)
  await prisma.user.upsert({
    where: { email: "admin@livrariadigital.com" },
    update: {},
    create: {
      name: "Admin",
      email: "admin@livrariadigital.com",
      password: adminPassword,
      role: "ADMIN",
    },
  })

  // Test users
  const userPassword = await bcrypt.hash("user123", 12)
  const users = await Promise.all([
    prisma.user.upsert({
      where: { email: "carlos@teste.com" },
      update: {},
      create: { name: "Carlos Silva", email: "carlos@teste.com", password: userPassword, cpf: "111.111.111-11" },
    }),
    prisma.user.upsert({
      where: { email: "ana@teste.com" },
      update: {},
      create: { name: "Ana Beatriz", email: "ana@teste.com", password: userPassword, cpf: "222.222.222-22" },
    }),
    prisma.user.upsert({
      where: { email: "pedro@teste.com" },
      update: {},
      create: { name: "Pedro Santos", email: "pedro@teste.com", password: userPassword, cpf: "333.333.333-33" },
    }),
  ])

  // Ebooks
  const ebooks = [
    {
      title: "JavaScript Moderno: Do Básico ao Avançado",
      slug: "javascript-moderno-do-basico-ao-avancado",
      author: "Lucas Martins",
      description: "Guia completo de JavaScript moderno cobrindo ES6+, async/await, módulos, TypeScript e frameworks modernos. Ideal para quem quer dominar a linguagem mais popular da web.",
      shortDescription: "Domine JavaScript de ponta a ponta com este guia prático e atualizado.",
      price: 49.90,
      originalPrice: 79.90,
      category: "Programação",
      tags: ["javascript", "typescript", "web", "frontend"],
      pages: 380,
      isbn: "978-65-0001-001-1",
      publisher: "Tech Books BR",
      status: "PUBLISHED" as const,
      featured: true,
      salesCount: 1250,
      avgRating: 4.8,
      reviewCount: 89,
    },
    {
      title: "React e Next.js na Prática",
      slug: "react-nextjs-na-pratica",
      author: "Fernanda Costa",
      description: "Aprenda a construir aplicações web modernas com React e Next.js. Server Components, App Router, streaming e muito mais.",
      shortDescription: "Construa apps web profissionais com React e Next.js.",
      price: 59.90,
      originalPrice: 89.90,
      category: "Programação",
      tags: ["react", "nextjs", "typescript", "fullstack"],
      pages: 420,
      isbn: "978-65-0001-002-8",
      publisher: "Tech Books BR",
      status: "PUBLISHED" as const,
      featured: true,
      salesCount: 980,
      avgRating: 4.9,
      reviewCount: 67,
    },
    {
      title: "Python para Data Science",
      slug: "python-para-data-science",
      author: "Ricardo Almeida",
      description: "Análise de dados, machine learning e visualização com Python. Inclui pandas, numpy, scikit-learn e matplotlib.",
      shortDescription: "Domine Python para ciência de dados e machine learning.",
      price: 67.90,
      originalPrice: 97.90,
      category: "Programação",
      tags: ["python", "data-science", "machine-learning"],
      pages: 450,
      isbn: "978-65-0001-003-5",
      publisher: "Data Press",
      status: "PUBLISHED" as const,
      featured: false,
      salesCount: 750,
      avgRating: 4.6,
      reviewCount: 45,
    },
    {
      title: "Marketing Digital: Estratégias que Funcionam",
      slug: "marketing-digital-estrategias-que-funcionam",
      author: "Juliana Mendes",
      description: "As estratégias de marketing digital mais eficientes para 2025. SEO, tráfego pago, e-mail marketing, redes sociais e funis de venda.",
      shortDescription: "Estratégias comprovadas de marketing digital para resultados reais.",
      price: 39.90,
      originalPrice: 59.90,
      category: "Marketing Digital",
      tags: ["marketing", "seo", "trafego-pago", "funil"],
      pages: 280,
      isbn: "978-65-0001-004-2",
      publisher: "Marketing Press",
      status: "PUBLISHED" as const,
      featured: true,
      salesCount: 2100,
      avgRating: 4.7,
      reviewCount: 156,
    },
    {
      title: "Copywriting: A Arte de Vender com Palavras",
      slug: "copywriting-arte-de-vender-com-palavras",
      author: "Roberto Nunes",
      description: "Técnicas de copywriting para páginas de vendas, e-mails, anúncios e redes sociais. Gatilhos mentais e persuasão ética.",
      shortDescription: "Aprenda a escrever textos que convertem visitantes em clientes.",
      price: 34.90,
      category: "Marketing Digital",
      tags: ["copywriting", "vendas", "persuasao"],
      pages: 220,
      isbn: "978-65-0001-005-9",
      publisher: "Marketing Press",
      status: "PUBLISHED" as const,
      featured: false,
      salesCount: 890,
      avgRating: 4.5,
      reviewCount: 72,
    },
    {
      title: "Instagram para Negócios",
      slug: "instagram-para-negocios",
      author: "Camila Rodrigues",
      description: "Como usar o Instagram para atrair clientes, criar autoridade e vender todos os dias. Estratégias de conteúdo, Reels e Stories.",
      shortDescription: "Transforme seu Instagram em uma máquina de vendas.",
      price: 29.90,
      category: "Marketing Digital",
      tags: ["instagram", "redes-sociais", "conteudo"],
      pages: 180,
      status: "PUBLISHED" as const,
      featured: false,
      salesCount: 1500,
      avgRating: 4.3,
      reviewCount: 98,
    },
    {
      title: "Do Zero ao Primeiro Milhão",
      slug: "do-zero-ao-primeiro-milhao",
      author: "André Oliveira",
      description: "O passo a passo para construir um negócio lucrativo do zero. Mentalidade empreendedora, validação de ideias, captação e gestão.",
      shortDescription: "Guia prático para empreendedores que querem escalar.",
      price: 79.90,
      originalPrice: 129.90,
      category: "Empreendedorismo",
      tags: ["empreendedorismo", "negocios", "startup"],
      pages: 350,
      isbn: "978-65-0001-007-3",
      publisher: "Empreenda Books",
      status: "PUBLISHED" as const,
      featured: true,
      salesCount: 1800,
      avgRating: 4.9,
      reviewCount: 134,
    },
    {
      title: "Lean Startup na Prática",
      slug: "lean-startup-na-pratica",
      author: "Marina Lima",
      description: "Como aplicar a metodologia Lean Startup no seu negócio brasileiro. MVP, validação, pivotagem e growth hacking.",
      shortDescription: "Aplique Lean Startup no contexto brasileiro.",
      price: 44.90,
      category: "Empreendedorismo",
      tags: ["lean-startup", "mvp", "growth"],
      pages: 250,
      isbn: "978-65-0001-008-0",
      publisher: "Empreenda Books",
      status: "PUBLISHED" as const,
      featured: false,
      salesCount: 620,
      avgRating: 4.4,
      reviewCount: 38,
    },
    {
      title: "E-commerce de Sucesso",
      slug: "ecommerce-de-sucesso",
      author: "Thiago Ferreira",
      description: "Tudo sobre e-commerce: plataformas, logística, pagamentos, marketing e atendimento. Do planejamento à primeira venda.",
      shortDescription: "Monte e escale seu e-commerce com estratégias comprovadas.",
      price: 54.90,
      originalPrice: 74.90,
      category: "Empreendedorismo",
      tags: ["ecommerce", "vendas-online", "logistica"],
      pages: 300,
      status: "PUBLISHED" as const,
      featured: false,
      salesCount: 530,
      avgRating: 4.2,
      reviewCount: 29,
    },
    {
      title: "Investimentos para Iniciantes",
      slug: "investimentos-para-iniciantes",
      author: "Patrícia Souza",
      description: "Guia completo para começar a investir: renda fixa, variável, fundos, cripto. Planejamento financeiro e independência.",
      shortDescription: "Comece a investir hoje mesmo com segurança e conhecimento.",
      price: 29.90,
      category: "Finanças Pessoais",
      tags: ["investimentos", "renda-fixa", "acoes", "cripto"],
      pages: 200,
      isbn: "978-65-0001-010-3",
      publisher: "Finanças Press",
      status: "PUBLISHED" as const,
      featured: false,
      salesCount: 1100,
      avgRating: 4.6,
      reviewCount: 85,
    },
    {
      title: "Liberdade Financeira em 5 Anos",
      slug: "liberdade-financeira-em-5-anos",
      author: "Marcos Andrade",
      description: "Plano prático para alcançar a independência financeira. Orçamento, eliminação de dívidas, investimentos e renda passiva.",
      shortDescription: "Seu plano personalizado rumo à independência financeira.",
      price: 39.90,
      originalPrice: 59.90,
      category: "Finanças Pessoais",
      tags: ["liberdade-financeira", "renda-passiva", "planejamento"],
      pages: 240,
      isbn: "978-65-0001-011-0",
      publisher: "Finanças Press",
      status: "PUBLISHED" as const,
      featured: true,
      salesCount: 950,
      avgRating: 4.7,
      reviewCount: 68,
    },
    {
      title: "Controle Financeiro Pessoal",
      slug: "controle-financeiro-pessoal",
      author: "Letícia Ramos",
      description: "Aprenda a organizar suas finanças, criar orçamentos e eliminar dívidas. Planilhas e ferramentas incluídas.",
      shortDescription: "Organize suas finanças e saia do vermelho de vez.",
      price: 19.90,
      category: "Finanças Pessoais",
      tags: ["financas", "orcamento", "dividas"],
      pages: 150,
      status: "PUBLISHED" as const,
      featured: false,
      salesCount: 2200,
      avgRating: 4.4,
      reviewCount: 190,
    },
    {
      title: "Produtividade Extrema",
      slug: "produtividade-extrema",
      author: "Diego Nascimento",
      description: "Técnicas avançadas de produtividade: GTD, Pomodoro, time blocking, deep work. Transforme sua rotina e alcance mais.",
      shortDescription: "Multiplique sua produtividade com técnicas comprovadas.",
      price: 34.90,
      category: "Produtividade",
      tags: ["produtividade", "gtd", "habitos"],
      pages: 210,
      isbn: "978-65-0001-013-4",
      publisher: "Produtividade Press",
      status: "PUBLISHED" as const,
      featured: false,
      salesCount: 780,
      avgRating: 4.5,
      reviewCount: 52,
    },
    {
      title: "Hábitos Atômicos Aplicados",
      slug: "habitos-atomicos-aplicados",
      author: "Renata Campos",
      description: "Como criar hábitos positivos e eliminar os negativos. Exercícios práticos e plano de 30 dias para transformação.",
      shortDescription: "Transforme sua vida um hábito por vez.",
      price: 27.90,
      category: "Produtividade",
      tags: ["habitos", "desenvolvimento-pessoal", "rotina"],
      pages: 190,
      status: "PUBLISHED" as const,
      featured: false,
      salesCount: 1400,
      avgRating: 4.8,
      reviewCount: 110,
    },
    {
      title: "Foco e Concentração no Mundo Digital",
      slug: "foco-e-concentracao-no-mundo-digital",
      author: "Bruno Teixeira",
      description: "Como manter o foco em uma era de distrações constantes. Técnicas de concentração, digital detox e mindfulness.",
      shortDescription: "Recupere seu foco na era das distrações digitais.",
      price: 24.90,
      category: "Produtividade",
      tags: ["foco", "concentracao", "mindfulness"],
      pages: 170,
      status: "PUBLISHED" as const,
      featured: false,
      salesCount: 650,
      avgRating: 4.3,
      reviewCount: 41,
    },
    {
      title: "Inteligência Artificial para Todos",
      slug: "inteligencia-artificial-para-todos",
      author: "Prof. Helena Santos",
      description: "Entenda IA sem ser programador. ChatGPT, Midjourney, automações e como usar IA no seu trabalho e negócio.",
      shortDescription: "Entenda e use IA no seu dia a dia profissional.",
      price: 44.90,
      originalPrice: 69.90,
      category: "Inteligência Artificial",
      tags: ["ia", "chatgpt", "automacao"],
      pages: 260,
      isbn: "978-65-0001-016-5",
      publisher: "AI Books BR",
      status: "PUBLISHED" as const,
      featured: true,
      salesCount: 3200,
      avgRating: 4.9,
      reviewCount: 245,
    },
    {
      title: "Prompt Engineering: Dominando a IA",
      slug: "prompt-engineering-dominando-a-ia",
      author: "Gabriel Freitas",
      description: "Técnicas avançadas de prompt engineering para ChatGPT, Claude, Gemini e outros LLMs. Crie prompts que geram resultados incríveis.",
      shortDescription: "Domine a arte de se comunicar com inteligências artificiais.",
      price: 39.90,
      category: "Inteligência Artificial",
      tags: ["prompt-engineering", "chatgpt", "llm"],
      pages: 200,
      isbn: "978-65-0001-017-2",
      publisher: "AI Books BR",
      status: "PUBLISHED" as const,
      featured: false,
      salesCount: 1800,
      avgRating: 4.7,
      reviewCount: 130,
    },
    {
      title: "Machine Learning com Python",
      slug: "machine-learning-com-python",
      author: "Prof. Roberto Lima",
      description: "De regressão linear a redes neurais. Implemente algoritmos de ML do zero e com scikit-learn, TensorFlow e PyTorch.",
      shortDescription: "Aprenda machine learning na prática com Python.",
      price: 89.90,
      originalPrice: 149.90,
      category: "Inteligência Artificial",
      tags: ["machine-learning", "python", "deep-learning"],
      pages: 520,
      isbn: "978-65-0001-018-9",
      publisher: "AI Books BR",
      status: "PUBLISHED" as const,
      featured: false,
      salesCount: 680,
      avgRating: 4.8,
      reviewCount: 48,
    },
    {
      title: "Node.js e APIs REST",
      slug: "nodejs-e-apis-rest",
      author: "Vinícius Carvalho",
      description: "Construa APIs robustas com Node.js, Express e Fastify. Autenticação, validação, testes e deploy. Do desenvolvimento à produção.",
      shortDescription: "APIs profissionais com Node.js do zero à produção.",
      price: 54.90,
      category: "Programação",
      tags: ["nodejs", "api", "backend", "express"],
      pages: 360,
      isbn: "978-65-0001-019-6",
      publisher: "Tech Books BR",
      status: "PUBLISHED" as const,
      featured: false,
      salesCount: 580,
      avgRating: 4.5,
      reviewCount: 36,
    },
    {
      title: "Banco de Dados: SQL e NoSQL",
      slug: "banco-de-dados-sql-e-nosql",
      author: "Adriana Pereira",
      description: "PostgreSQL, MySQL, MongoDB e Redis na prática. Modelagem, queries avançadas, indexação e otimização de performance.",
      shortDescription: "Domine bancos de dados relacionais e não-relacionais.",
      price: 9.90,
      category: "Programação",
      tags: ["sql", "nosql", "postgresql", "mongodb"],
      pages: 320,
      isbn: "978-65-0001-020-2",
      publisher: "Tech Books BR",
      status: "PUBLISHED" as const,
      featured: false,
      salesCount: 420,
      avgRating: 4.4,
      reviewCount: 25,
    },
  ]

  for (const ebook of ebooks) {
    await prisma.ebook.upsert({
      where: { slug: ebook.slug },
      update: {},
      create: ebook,
    })
  }

  // Sample reviews
  const ebookSlugs = ["javascript-moderno-do-basico-ao-avancado", "marketing-digital-estrategias-que-funcionam", "do-zero-ao-primeiro-milhao"]
  for (const slug of ebookSlugs) {
    const ebook = await prisma.ebook.findUnique({ where: { slug } })
    if (!ebook) continue

    await prisma.review.create({
      data: {
        userId: users[0].id,
        ebookId: ebook.id,
        rating: 5,
        comment: "Excelente conteúdo! Muito bem escrito e atualizado.",
        approved: true,
      },
    }).catch(() => {})

    await prisma.review.create({
      data: {
        userId: users[1].id,
        ebookId: ebook.id,
        rating: 4,
        comment: "Muito bom! Recomendo para quem está começando.",
        approved: true,
      },
    }).catch(() => {})
  }

  // Coupons
  await prisma.coupon.upsert({
    where: { code: "BEMVINDO10" },
    update: {},
    create: {
      code: "BEMVINDO10",
      discountType: "PERCENTAGE",
      discountValue: 10,
      maxUses: 1000,
      active: true,
    },
  })

  await prisma.coupon.upsert({
    where: { code: "LANCAMENTO20" },
    update: {},
    create: {
      code: "LANCAMENTO20",
      discountType: "PERCENTAGE",
      discountValue: 20,
      maxUses: 500,
      minPurchase: 50,
      active: true,
      expiresAt: new Date("2026-12-31"),
    },
  })

  await prisma.coupon.upsert({
    where: { code: "GRATIS100" },
    update: {},
    create: {
      code: "GRATIS100",
      discountType: "PERCENTAGE",
      discountValue: 100,
      maxUses: 10000,
      active: true,
    },
  })

  console.log("Seed completed successfully!")
  console.log(`Created: ${ebooks.length} ebooks, 4 users, 3 coupons, reviews`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
